#!/usr/bin/env python3
"""Export the world interface's Blockbench model to the geometry the client bakes.

Reads ``docs/art/world_interface/world_interface.bbmodel`` (the editing source), re-packs its UV
islands so the painter and the model agree on every offset, writes the offsets back into the
bbmodel, and emits:

* ``src/main/resources/assets/thefourthfrequency/models/entity/world_interface.json`` - Java-space
  bones and cubes, read by ``WorldInterfaceGeometry`` on the client.
* ``docs/art/world_interface/layout.txt`` - one line per island: ``name u v probe_x probe_y``,
  where the probe is a texel inside the island's painted north face on the base sheet.
  ``ResourceContractTest`` reads it to prove the sheets and the model were generated together.

Run this, then ``paint_world_interface_textures.py``; the two must be regenerated as a pair.
"""

from __future__ import annotations

import json
from pathlib import Path

from world_interface_model import ART_DIR, ROOT, face_rects, load, pack, save, to_runtime

BBMODEL = ART_DIR / "world_interface.bbmodel"
GEOMETRY = ROOT / "src/main/resources/assets/thefourthfrequency/models/entity/world_interface.json"
LAYOUT = ART_DIR / "layout.txt"
TEXTURE = ROOT / "src/main/resources/assets/thefourthfrequency/textures/entity/world_interface_form_1.png"
# Texels per UV unit on the base sheets; the painter uses the same number.
BASE_SCALE = 4


def main() -> None:
    model = load(BBMODEL)
    islands = pack(model)
    # Embed the first form's base sheet so Blockbench opens the model textured. The painter runs
    # after this script, so on a fresh model the sheet is the previous one; run both twice.
    save(model, BBMODEL, texture_png=TEXTURE if TEXTURE.exists() else None)
    geometry = to_runtime(model)
    GEOMETRY.parent.mkdir(parents=True, exist_ok=True)
    GEOMETRY.write_text(json.dumps(geometry, separators=(",", ":")) + "\n", encoding="utf-8")

    lines = [
        "# GENERATED by tools/export_world_interface_model.py from world_interface.bbmodel.",
        "# name u v probe_x probe_y -- probe is a texel inside the island's painted north face.",
        f"# canvas {model.resolution[0]}x{model.resolution[1]} "
        f"png {model.resolution[0] * BASE_SCALE}x{model.resolution[1] * BASE_SCALE} density {BASE_SCALE}",
    ]
    for island in sorted(islands, key=lambda i: i.name):
        x0, y0, x1, y1 = face_rects((island.uv, island.size, island.mirror), BASE_SCALE)["north"]
        probe_x = min(x1 - 1, x0 + max(0, (x1 - x0) // 2))
        probe_y = min(y1 - 1, y0 + max(0, (y1 - y0) // 2))
        lines.append(f"{island.name} {island.uv[0]:g} {island.uv[1]:g} {probe_x} {probe_y}")
    LAYOUT.write_text("\n".join(lines) + "\n", encoding="utf-8")

    bones = geometry["bones"]
    cubes = sum(len(bone["cubes"]) for bone in bones)
    print(f"{GEOMETRY.relative_to(ROOT)}: {len(bones)} bones, {cubes} cubes, {len(islands)} islands "
          f"on {model.resolution[0]}x{model.resolution[1]}")


if __name__ == "__main__":
    main()
